### ISSUE TITLE
unable to build ca branch patcher

### ISSUE THREAD

**Issue by ghost** [OpenShopChannel/WSC-Patcher#3]
log

C:\Users\purpe\Downloads\WSC-Patcher-resolve-generated-ca>go build
build github.com/OpenShopChannel/WSC-Patcher: cannot load embed: malformed module path "embed": missing dot in first path element

C:\Users\purpe\Downloads\WSC-Patcher-resolve-generated-ca>

**Comment by spotlightishere** [comment]
Hi, thank you for the report. Can you please verify with `go version` that you're using Go 1.17 or later?

**Comment by ghost** [comment]
Ok i tried go version
1.17 and 1.17.2

**Comment by spotlightishere** [comment]
Thank you for checking!

Unfortunately, I'm unable to reproduce this issue with Go 1.17 and 1.18.
Can you please let me know what platform you're building this program on, and how you installed Go?

(Wonder if it might help to upgrade to 1.18.0 or 1.17.8 as well - may not resolve your issue, but it's worth keeping up to date :)

**Comment by spotlightishere** [comment]
Going to close as this is hopefully no longer an issue - please feel free to comment or open a new issue if the problem persists!
