### ISSUE TITLE
MD5 Hash Isn't the Same

### ISSUE THREAD

**Issue by wish13yt** [OpenShopChannel/WSC-Patcher#5]
I am using https://md5-checksum.com/.
I am using an ARM64 system.
The MD5 checksum downloaded is: cee80a6376082b1cc4d602885faff086
The MD5 shown is: 5bab26da1b8430108a80bc584de334e6

**Comment by dakrk** [comment]
Not only is the `cee80a6376082b1cc4d602885faff086` checksum one from an AMD64 Windows build, rather than a ARM64 Windows build, but the `5bab26da1b8430108a80bc584de334e6` checksum you provided does not match any files listed on the v1.3.0 release page.

**Comment by wish13yt** [comment]
I'm sorry, I meant AMD64
