### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lyoneofficial** [OpenShopChannel/WSC-Patcher#6]
![image](https://github.com/OpenShopChannel/WSC-Patcher/assets/87578373/9c5c9b6b-c308-46f4-b14c-caf785927d87)

**Comment by Artuto** [comment]
You most likely have a corrupt cached file. Delete the `cache` directory and try again. Likely not a bug.

**Comment by noahpistilli** [comment]
> You most likely have a corrupt cached file

It is probably more likely to be a URL size that is greater than 12 characters.

**Comment by Artuto** [comment]
> > You most likely have a corrupt cached file
> 
> It is probably more likely to be a URL size that is greater than 12 characters.

It prechecks that
https://github.com/OpenShopChannel/WSC-Patcher/blob/main/main.go#L50-L51
