### ISSUE TITLE
Error while installing patched WAD on a WAD Manager or Dolphin Emulator

### ISSUE THREAD

**Issue by lyoneofficial** [OpenShopChannel/WSC-Patcher#7]
Hi when I try to install the patched WAD on a real Wii and Wii U and Dolphin Emulator the WAD Manager and Dolphin refuses to install it giving an error of signature.

**Comment by lyoneofficial** [comment]
![image](https://github.com/OpenShopChannel/WSC-Patcher/assets/87578373/f79022f4-9d75-4f9f-a226-cf7d6954cbe2)

**Comment by Artuto** [comment]
Not a patcher bug.
