### ISSUE TITLE
Wii Shop Channel Deleting every title

### ISSUE THREAD

**Issue by Ocarinaoftime** [OpenShopChannel/WSC-Patcher#9]
So, when launching WSC and doing all of the EC related functions when logging in, after GetETickets, the WSC does `showInitialPage(false, true)`, W_01 loads, and then when I go to reset the channel through either the home menu or the reset button, my Wii gets stuck on a black screen, indicating that there is no content for 48414241 (WSC). When going to the Wii Menu, everything is gone except for the disc channel. I have to use WilBrand / Letterbomb to open BootMii and restore a nand backup to get everything back. When I get the chance, I will dump the EC Log from my Wii and upload it to pastebin and link it here.

**Comment by Artuto** [comment]
Definitely cannot reproduce.

**Comment by Ocarinaoftime** [comment]
Just asking, why are all titles and tickets being marked as managed? There is still a possibility of ec::removeAllTitles well... removing all titles because according to the docs, 

> Its return value is seemingly the amount of titles remaining.

So if its return value is NOT the amount of titles remaining, then it is looping through the managed titles and tickets and deleting them. If you didn't mark all titles and tickets as managed, then ec::removeAllTitles would do no damage at all because no titles or tickets are managed.
